### ISSUE TITLE
Testing documentation & automatic builds

### ISSUE THREAD

**Issue by cannotparse** [CommunicationsSecurityEstablishment/spartacus#19]
Within spartacus there are a plethora of test cases for various components. However, there aren't instructions for contributions or running test cases. While most of these conveniently include a script comment for running from command line, it would be good to adopt/publish a standard way of run these tests. If this is provided, then services such as [travis-ci](https://travis-ci.org/) can automatically verify pull requests.

**Comment by cannotparse** [comment]
[Nosetests](http://nose.readthedocs.io/en/latest/) is a pretty great library which I'd recommend. It already finds and runs 19 of them. (Some of these are currently failing)

**Comment by pg-cse** [comment]
@cannotparse Thanks for reporting this. I'm currently using pycharm and it allows me to do a full run of all the tests that are written. Last I checked, I was not getting any fail at the moment. Could you expand a bit on the tests that are failing? 

I will look into integrating something better to run the tests. As more people get involved I do think this will be required.

**Comment by cannotparse** [comment]
Seems like pycharm runs something equivalent to `python3 -m unittest`. Runs all 80 tests perfectly.
