### ISSUE TITLE
Changes to parser file make tests fail

### ISSUE THREAD

**Issue by kommisar5150** [CommunicationsSecurityEstablishment/spartacus#27]
I did some fixes to expected output/input for the test_Parser.py file. As is, two of the tests are failing because we changed the input for certain functions to include `rawLine`. For example, line 1035:

`self.parser._evaluateAndExtractInfoFromLine(["XOR", "#0xFF", "$B", ";test"], buildInstruction)`

This test fails because extra rawLine argument passed into the function is missing. We can just add a generic line to fill since it's trivial what the rawLine contains in this context.

`self.parser._evaluateAndExtractInfoFromLine(["XOR", "#0xFF", "$B", ";test"], buildInstruction, "")`

Also at line 964 in test_Parser.py fails the test
`self.assertEqual(buildInstruction.operationMnemonic, "None")`

because now the operationMnemonic holds the label name. It's an easy fix, just need to change the expected value to be : 
`self.assertEqual(buildInstruction.operationMnemonic, "TEST:")`

**Comment by pg-cse** [comment]
Good catch @kommisar5150

**Comment by pg-cse** [comment]
Fixed in https://github.com/CommunicationsSecurityEstablishment/spartacus/pull/28
