### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by komiljon27** [CommunicationsSecurityEstablishment/spartacus#6]
When I tried to use the Debugger.py I keep getting segmentation error. The error was
"0x40000000 : MOV #0x20001000 $A 
('hello.bin',): Segmentation fault: 11"

My process to run the program was: first I used the Assembler.py and second was Linker.py and so far there was no errors. When I got to the third step, running the Debugger.py I got the error. 

OS I'm using: macOS High Sierra Version 10.13.2
Python I'm using: Python3 version 3.6.4(downloaded from https://www.python.org/downloads/release/python-364/)

Thanks.

**Comment by pg-cse** [comment]
Hi, thank you for reporting this. _Segmentation fault: 11_ error does not seem to be originating from Spartacus it self. It appears to possibly be an issue with the setup you are currently using. After doing a search about related issues, it seems MacOS users have similar issues using various popular projects. For many users, reinstalling the faulty application seems to be fixing these issues (python in this case). 

Could you please reinstall python and validate that the following MacOs python provided guidelines are followed: 
https://www.python.org/download/mac/tcltk/

The application seem to crash after the machine have booted up while the debugger is waiting on further instructions. One of the other threads running at that time is related to tkinter so it would be logical for tk to be the issue in this case. Please let me know if this fixes this specific issue.

Thank you again for reporting this.

**Comment by pg-cse** [comment]
This issue is now considered as closed. Please re-open if provided guidance does not work.
