### ISSUE TITLE
Printing issues on terminal

### ISSUE THREAD

**Issue by kommisar5150** [CommunicationsSecurityEstablishment/spartacus#7]
The terminal is intended to print ASCII 0x00 (null) as a blank character, which is specified in the following path:

spartacus/CapuaEnvironment/IOComponent/MemoryMappedDevices/Terminal/Terminal.py

The terminal’s first character memory location is at 0x20001000, and the entire terminal has an 80x25 display. Printing two unique characters at locations 0x20001000 and 0x2000104F (+79) should display the characters at both extremities of the first line. Using Windows 10, this null character does not seem to print a single space character correctly. In this case, the second character prints ¾ up the line instead of the end. This issue is remedied by changing the value on line 56 of Terminal.py from 0x00 to 0x20, which is the ASCII character for a blank space. 

Additional tests were done on a Linux OS (Ubuntu), and while the character positioning worked well for 0x00, the null characters printed square symbols instead of blank spaces. Testing other non-printable characters between ASCII 0x00 and 0x20 shows varying results between Windows and Linux, suggesting that OS, Python version, and Tkinter versions are all variables that may change the output. All tests were done using Python 3.6.5 and Tkinter 8.6. Using ASCII character 0x20 seems to work reliably in both OS environments.

**Comment by pg-cse** [comment]
Thank you for reporting the issue. Will fix this as soon as I have moment for it.

**Comment by pg-cse** [comment]
Change for this is present in following pull request. This will be merged in as soon as the full pull request can be merged.
https://github.com/CommunicationsSecurityEstablishment/spartacus/pull/8

**Comment by pg-cse** [comment]
This pull request was merged effectively fixing this issue.
https://github.com/CommunicationsSecurityEstablishment/spartacus/pull/10
